PessoasInfo/Controllers/GraficosController.cs
using PessoasInfo.Services;

namespace PessoasInfo.Controllers;

public class GraficosController : Controller
{
    private readonly AppDbContext _context;

    public GraficosController(AppDbContext context)
    {
        _context = context;
    }

    [Authorize(Policy = "OnlyAdminChecker")]
    public async Task<IActionResult> SimpleGraph()
    {
        var graphService = new GraphService(_context);
        var graph = await graphService.GenerateGraph();
        return await Task.Run(() => View(graph));
    }
}

PessoasInfo/Controllers/PessoasController.cs
using PessoasInfo.ViewModels.Pessoa;

namespace PessoasInfo.Controllers;

public class PessoasController : Controller
{
    private readonly IPagingService _pagingService;
    private readonly IPessoaRepository _pessoaRepository;

    public PessoasController(IPessoaRepository pessoaRepository, IPagingService pagingService)
    {
        _pessoaRepository = pessoaRepository;
        _pagingService = pagingService;
    }

    // Get Pessoas
    [HttpGet]
    public async Task<IActionResult> Index()
    {
        var pessoas = await _pessoaRepository.GetPessoas();
        return pessoas != null
            ? await Task.Run(() => View(pessoas))
            : NoContent();
    }

    // Paged Pessoas
    [HttpGet]
    [Authorize(Roles = "Comum, Admin")]
    public async Task<IActionResult> PagedIndex(string searchString, string sortOrder, int pageIndex = 1)
    {
        ViewBag.NomeSortParam = string.IsNullOrEmpty(sortOrder) ? "nome_desc" : "";
        ViewBag.IdSortParam = string.IsNullOrEmpty(sortOrder) ? "id_desc" : "";
        ViewBag.CurrentFilter = searchString;

        var pessoas = await _pagingService.PagingPessoas(searchString, sortOrder, pageIndex);
        return pessoas != null
            ? await Task.Run(() => View(pessoas))
            : NoContent();
    }

    // Paged Pessoas Cruzadas
    public async Task<IActionResult> AllDetails(int pageIndex = 1)
    {
        var pessoasCruzadas = await _pagingService.PagingPessoasInnerJoinEF(pageIndex);
        return pessoasCruzadas != null
            ? await Task.Run(() => View(pessoasCruzadas))
            : NoContent();
    }

    // Detalhe de uma pessoa 
    [HttpGet]
    [Authorize(Policy = "TestClaims")]
    public async Task<IActionResult> Details(int id)
    {
        if (id == null || id <= 0)
            return NotFound();

        var pessoa = await _pessoaRepository.GetPessoa(id);

        return await Task.Run(() => View(pessoa));
    }

    // Adicionar nova pessoa
    [HttpGet]
    [Authorize(Policy = "TestClaims")]
    public async Task<IActionResult> Create()
    {
        return await Task.Run(View);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(PessoaCreateViewModel pessoaCreateViewModel)
    {
        if (!ModelState.IsValid)
            return BadRequest();

        await _pessoaRepository.AddPessoa(pessoaCreateViewModel);

        return await Task.Run(() => RedirectToAction(nameof(Index)));
    }

    // Editar pessoa
    [HttpGet]
    [Authorize(Policy = "TestClaims")]
    public async Task<IActionResult> Edit(int id)
    {
        if (id == null || id <= 0)
            return NotFound();

        var pessoa = await _pessoaRepository.GetPessoa(id);

        return await Task.Run(() => View(pessoa));
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, PessoaEditViewModel pessoaEditViewModel)
    {
        if (id != pessoaEditViewModel.PessoaId)
            return NotFound();

        if (!ModelState.IsValid)
            return BadRequest();

        await _pessoaRepository.UpdatePessoa(id, pessoaEditViewModel);

        return await Task.Run(() => RedirectToAction(nameof(Index)));
    }

    // Delete Pessoa
    [HttpGet]
    [Authorize(Policy = "TestClaims")]
    public async Task<IActionResult> Delete(int id)
    {
        var pessoa = await _pessoaRepository.GetPessoa(id);

        if (id == null || pessoa == null)
            return NotFound();

        return await Task.Run(() => View(pessoa));
    }

    [HttpPost]
    [ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var pessoa = await _pessoaRepository.GetPessoa(id);

        if (id == null || pessoa == null)
            return NotFound();

        await _pessoaRepository.DeletePessoa(id);

        return await Task.Run(() => RedirectToAction(nameof(Index)));
    }
}

PessoasInfo/Controllers/RolesController.cs
using PessoasInfo.Services;
using PessoasInfo.ViewModels.Role;

namespace PessoasInfo.Controllers;

public class RolesController : Controller
{
    private readonly AppDbContext _context;
    private readonly RoleManager<IdentityRole> _roleManager;
    private readonly UserManager<AppUser> _userManager;


    public RolesController(AppDbContext context, UserManager<AppUser> userManager,
        RoleManager<IdentityRole> roleManager)
    {
        _context = context;
        _roleManager = roleManager;
        _userManager = userManager;
    }

    [HttpGet]
    [Authorize(Policy = "OnlyAdminChecker")]
    public async Task<IActionResult> Index()
    {
        var roles = await _context.Roles.ToListAsync();
        return await Task.Run(() => View(roles));
    }

    // Upsert
    [HttpGet]
    [Authorize(Policy = "OnlyAdminChecker")]
    public async Task<IActionResult> Upsert(string id)
    {
        if (string.IsNullOrEmpty(id)) return View();

        var user = await _context.Roles.FirstOrDefaultAsync(x => x.Id == id);
        return await Task.Run(() => View(user));
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Upsert(RoleViewModel roleViewModel)
    {
        if (!ModelState.IsValid)
            return BadRequest();

        // Cargo já existe
        if (await _roleManager.RoleExistsAsync(roleViewModel.Name))
            return await Task.Run(() => RedirectToAction("Index"));

        var roleService = new EditRoleService(_context, _roleManager);

        await roleService.Upsert(roleViewModel);

        return await Task.Run(() => RedirectToAction(nameof(Index)));
    }

    // Deletar cargo
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Delete(string id)
    {
        var editRoleService = new EditRoleService(_context, _roleManager);

        if (id == null)
            return await Task.Run(() => RedirectToAction(nameof(Index)));

        if (ModelState.IsValid)
            await editRoleService.Delete(id);

        return await Task.Run(() => RedirectToAction(nameof(Index)));
    }
}

PessoasInfo/Controllers/UsersController.cs
using PessoasInfo.Services;
using PessoasInfo.ViewModels.UserClaim;

namespace PessoasInfo.Controllers;

public class UsersController : Controller
{
    private readonly AppDbContext _context;
    private readonly UserManager<AppUser> _userManager;

    public UsersController(AppDbContext context, UserManager<AppUser> userManager)
    {
        _context = context;
        _userManager = userManager;
    }

    [HttpGet]
    public async Task<IActionResult> Index()
    {
        var userList = await _context.AppUsers.ToListAsync();
        var roleList = await _context.UserRoles.ToListAsync();
        var roles = await _context.Roles.ToListAsync();

        // Caso usuário não tenha cargo, coloca um placeholder "N/A"
        foreach (var user in userList)
        {
            var role = roleList.FirstOrDefault(x => x.UserId == user.Id);
            if (role == null)
                user.Role = "N/A";

            else
                user.Role = roles.FirstOrDefault(x => x.Id == role.RoleId).Name;
        }

        return await Task.Run(() => View(userList));
    }

    /// <summary>
    ///     Busca pelo usuário e seu cargo
    /// </summary>
    /// <param name="userId"></param>
    /// <returns>Em seguida mostra seu cargo através de uma lista de SelectListItem</returns>
    [HttpGet]
    public async Task<IActionResult> Edit(string userId)
    {
        if (userId != null)
        {
            var editUserService = new EditUserService(_context, _userManager);

            var user = await editUserService.EditUserGet(userId);

            return await Task.Run(() => View(user));
        }

        return await Task.Run(View);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(AppUser appUser)
    {
        if (ModelState.IsValid)
        {
            var editUserService = new EditUserService(_context, _userManager);
            await editUserService.EditUserPost(appUser);

            return await Task.Run(() => RedirectToAction(nameof(Index)));
        }

        return await Task.Run(() => View(appUser));
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Delete(string userId)
    {
        if (ModelState.IsValid)
        {
            var editUserService = new EditUserService(_context, _userManager);
            await editUserService.DeleteUser(userId);

            return await Task.Run(() => RedirectToAction(nameof(Index)));
        }

        return await Task.Run(() => RedirectToAction("Error", "Home"));
    }

    // User Claims
    [HttpGet]
    public async Task<IActionResult> ManageUserClaims(string userId)
    {
        var user = await _userManager.FindByIdAsync(userId);

        if (user == null)
            return NotFound();

        // Busca por permissões associadas ao usuário em questão
        var existingUserClaims = await _userManager.GetClaimsAsync(user);

        var model = new UserClaimsViewModel
        {
            UserId = userId
        };

        foreach (var claim in ClaimStore.ClaimList)
        {
            var userClaim = new UserClaim
            {
                ClaimType = claim.Type
            };

            // Verifica se existe claims associados a um usuário
            if (existingUserClaims.Any(x => x.Type == claim.Type)) userClaim.IsSelected = true;

            model.Claims.Add(userClaim);
        }

        return await Task.Run(() => View(model));
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> ManageUserClaims(UserClaimsViewModel userClaimsViewModel)
    {
        if (!ModelState.IsValid)
            return BadRequest();

        var manageUserClaimsService = new ManageUserClaimsService(_userManager);

        await manageUserClaimsService.ManageClaims(userClaimsViewModel);

        return RedirectToAction(nameof(Index));
    }
}

PessoasInfo/Views/Shared/_Layout.cshtml
@inject SignInManager<AppUser> SignInManager
@inject UserManager<AppUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - PessoasInfo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/css/flatly.min.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/PessoasInfo.styles.css" asp-append-version="true"/>
    <link rel="shortcut icon" type="image/x-icon" href="~/favicon.ico"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PessoasInfo</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link active text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>

                    @* Ademar *@
                    @if (SignInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                    {
                        <li class="nav-item">
                            <a class="nav-link text-light">Olá, @(UserManager.GetUserName(User))</a>
                        </li>
                        <span>&nbsp;</span>
                        <li class="nav-item border border-light bg-danger small bg-opacity-75 rounded-1">
                            <a class="nav-link text-white" asp-controller="Accounts" asp-action="Logout">LogOff</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-light" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Vizualizar Cadastros</a>
                            <div class="dropdown-menu">
                                <a id="Listar" class="dropdown-item" asp-area="" asp-controller="Pessoas" asp-action="Index">Pessoas</a>
                                <a id="ListarDetalhes" class="dropdown-item" asp-area="" asp-controller="Detalhes" asp-action="Index">Detalhes</a>
                                <a id="ListarTelefones" class="dropdown-item" asp-area="" asp-controller="Telefones" asp-action="Index">Telefones</a>
                                <a id="ListarPessoasCruzadas" class="dropdown-item" asp-area="" asp-controller="Pessoas" asp-action="AllDetails">Pessoas Cruzadas</a>
                                @* Aqui será chamado a action responsável pelo INNER JOIN entre as 3 tabelas *@
                                <div class="dropdown-divider"></div>
                                <a id="ListarPessoasPaginado" class="dropdown-item" asp-area="" asp-controller="Pessoas" asp-action="PagedIndex">Pessoas Paginado</a>
                                <a id="ListarDetalhesPaginado" class="dropdown-item" asp-area="" asp-controller="Detalhes" asp-action="PagedIndex">Detalhes Paginado</a>
                                <a id="ListarTelefonesPaginado" class="dropdown-item" asp-area="" asp-controller="Telefones" asp-action="PagedIndex">Telefones Paginado</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-light" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Adicionar novos Dados</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-area="" asp-controller="Pessoas" asp-action="Create">Nova Pessoa</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Detalhes" asp-action="Create">Novo Detalhe</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Telefones" asp-action="Create">Novo Telefone</a>
                            </div>
                        </li>
                        <ul class="nav">
                            <li class="nav-pills">
                            <a class="nav-link border-success text-white bg-secondary text-md-center" aria-current="page" asp-controller="Graficos" asp-action="SimpleGraph">Gerar Gráfico</a>
                        </ul>
                        <span>&nbsp;</span>
                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Relatórios
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                <li>
                                    <a class="dropdown-item" asp-controller="Relatorios" asp-action="CreateReport">Gerar Relatório</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-controller="Relatorios" asp-action="Index">Listar Relatórios</a>
                                </li>
                            </ul>
                        </div>
                        <span>&nbsp;</span>
                        <ul class="nav">
                            <li class="nav-pills">
                            <a id="btnUsers" type="button" class="btn btn-outline-light" aria-current="page" asp-controller="Users" asp-action="Index">Listar Usuários</a>
                        </ul>
                        <span>&nbsp;</span>
                        <ul class="nav">
                            <li class="nav-pills">
                            <a id="btnUsers" type="button" class="btn btn-outline-warning" aria-current="page" asp-controller="Roles" asp-action="Index">Listar Cargos</a>
                        </ul>
                        <span>&nbsp;</span>
                        <li class="nav-item border border-light bg-success bg-opacity-75 rounded-1">
                            <a class="nav-link text-white" asp-area="" asp-controller="Accounts" asp-action="Register">Registrar Novo Usuário</a>
                        </li>
                    }
                    @* Usuário com pefil comum *@
                    @if (SignInManager.IsSignedIn(User) && User.IsInRole("Comum"))
                    {
                        <li class="nav-item">
                            <a class="nav-link text-light">Olá, @(UserManager.GetUserName(User))</a>
                        </li>
                        <span>&nbsp;</span>
                        <li class="nav-item border border-light bg-danger small bg-opacity-75 rounded-1">
                            <a class="nav-link text-white" asp-controller="Accounts" asp-action="Logout">LogOff</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-light" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Vizualizar Cadastros</a>
                            <div class="dropdown-menu">
                                <a id="ListarPessoasPaginado" class="dropdown-item" asp-area="" asp-controller="Pessoas" asp-action="PagedIndex">Pessoas Paginado</a>
                                <a id="ListarDetalhesPaginado" class="dropdown-item" asp-area="" asp-controller="Detalhes" asp-action="PagedIndex">Detalhes Paginado</a>
                                <a id="ListarTelefonesPaginado" class="dropdown-item" asp-area="" asp-controller="Telefones" asp-action="PagedIndex">Telefones Paginado</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-light" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Adicionar novos Dados</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-area="" asp-controller="Pessoas" asp-action="Create">Nova Pessoa</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Detalhes" asp-action="Create">Novo Detalhe</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Telefones" asp-action="Create">Novo Telefone</a>
                            </div>
                        </li>
                    }
                    @* Usuário com perfil básico *@

                    @if (SignInManager.IsSignedIn(User) && User.IsInRole("Basico"))
                    {
                        <li class="nav-item">
                            <a class="nav-link text-light">Olá, @(UserManager.GetUserName(User))</a>
                        </li>
                        <span>&nbsp;</span>
                        <li class="nav-item border border-light bg-danger small bg-opacity-75 rounded-1">
                            <a class="nav-link text-white" asp-controller="Accounts" asp-action="Logout">LogOff</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-light" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Vizualizar Cadastros</a>
                            <div class="dropdown-menu">
                                <a id="Listar" class="dropdown-item" asp-area="" asp-controller="Pessoas" asp-action="Index">Pessoas</a>
                                <a id="ListarDetalhes" class="dropdown-item" asp-area="" asp-controller="Detalhes" asp-action="Index">Detalhes</a>
                                <a id="ListarTelefones" class="dropdown-item" asp-area="" asp-controller="Telefones" asp-action="Index">Telefones</a>
                                <a id="ListarPessoasCruzadas" class="dropdown-item" asp-area="" asp-controller="Pessoas" asp-action="AllDetails">Pessoas Cruzadas</a>
                            </div>
                        </li>
                    }

                    @* Usuário não logado e não autenticado *@
                    @if (!SignInManager.IsSignedIn(User))
                    {
                        <span>&nbsp;</span>
                        <li class="nav-item border border-light small bg-info bg-opacity-50 rounded-1">
                            <a class="nav-link text-white" asp-area="" asp-controller="Accounts" asp-action="Login">Login</a>
                        </li>
                        <span>&nbsp;</span>
                    }
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<div id="CarregandoLista" class="text-center" style="display: none">
    <img width="15%" src="~/Content/Images/Carregando.gif" class="rounded border p-5 border bordedr rounded-1 border-secondary-subtle" alt="">
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - PessoasInfo - <a href="https://github.com/JGMelon22/PessoasInfo">Repository</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", false)
</body>
</html>