PessoasInfo/Controllers/AccessesController.cs
namespace PessoasInfo.Controllers;

public class AccessesController : Controller
{
    // Autorização via cookie - Basta estar logado
    [Authorize]
    public async Task<IActionResult> Index()
    {
        return await Task.Run(View);
    }

    // Por política - Verifica se o usuário é admin ou não
    [Authorize(Policy = "OnlyAdminChecker")]
    public IActionResult OnlyAdminChecker()
    {
        return View();
    }

    // Autenticação por claim
    [Authorize(Policy = "TestClaims")]
    public IActionResult CheckClaims()
    {
        return View();
    }

    // Apenas usuário não logado
    [AllowAnonymous]
    public IActionResult AnonymousUser()
    {
        return View();
    }
}

PessoasInfo/Controllers/HomeController.cs
using System.Diagnostics;

namespace PessoasInfo.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

PessoasInfo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-md-start">
    <h4 class="display-6 fst-italic"></h4>
    <main role="main" class="container">
        <h2 class="mt-5 fst-italic">PessoasInfo</h2>
        <p class="lead">De um simples usuário Linux para o mundo 🐧🌎<br/><code>Em memória de um grande amigo: Cristiano Noronha</code></p>
    </main>
</div>

@if (User.Identity.IsAuthenticated)
{
    @if (User.IsInRole("Admin"))
    {
        <h4 class="text-success text-sm-start">Usuário Admin</h4>
    }

    else if (User.IsInRole("Comum"))
    {
        <h4 class="text-info text-sm-start">Usuário comum</h4>
    }

    else
    {
        <h4 class="text-black text-sm-start">Usuário básico</h4>
    }
}

@* <a class="btn btn-info small rounded-pill" asp-controller="Accesses" asp-action="AnonymousUser">Usuário Anônimo</a> *@
@* <a class="btn btn-success small rounded-pill" asp-controller="Accesses" asp-action="OnlyAdminChecker">Somente Adms</a> *@
@* <a class="btn btn-warning small rounded-pill" asp-controller="Accesses" asp-action="CheckClaims">Permissão de Criação</a> *@